// src/components/Dashboard/Dashboard.vue
<template>
  <aside class="col">
    <h2>Tableau de bord</h2>
    <div class="nav">
      <router-link to="/account" class="item-link"
        ><i class="fas fa-user-circle"></i> Mon Compte</router-link
      >
      <router-link to="/jobs" class="item-link"
        ><i class="far fa-envelope-open"></i> Les candidatures</router-link
      >
      <router-link to="/application" class="item-link">
        <PlusCircle />
        J'ai postulé</router-link
      >
      <router-link to="/relance" class="item-link" v-if="relance">
        <span class="fa-layers fa-fw">
          <i class="fas fa-bell"></i>
          <span class="fa-layers-counter" style="background:Tomato">
            {{ relance }}</span
          >
        </span>
        Mes relances
        <!-- <i class="far fa-bell"></i>
        <small class="text-danger">{{ relance }} </small> - Mes
        relances-->
      </router-link>
      <router-link v-else></router-link>
    </div>
  </aside>
</template>

<script>
import PlusCircle from "../../svg/PlusCircle";
export default {
  name: "Dashboard",
  components: {
    PlusCircle,
  },
  data: () => ({
    relance: "5",
  }),
};
</script>

<style scoped>
aside {
  background: #01212c;
  height: 100vh;
}
h2 {
  text-align: center;
  margin-top: 2vh;
  color: white;
}
.nav {
  display: grid;
  margin-top: 20vh;
}
.item-link {
  display: flex;
  justify-content: center;
  align-items: center;
  color: white;
  height: 4em;
  font-size: 1.4em;
}
.item-link:hover {
  background: rgb(24, 30, 56);
}

svg {
  margin-right: 5px;
}
.item-link span {
  margin-right: 5px;
}
.fa-layers-counter {
  right: -7px !important;
  font-size: 45px !important;
}
/* .fa-layers-counter {
  right: -8px !important;
  font-size: 45px !important;
  padding-left: 25px;
  padding-right: 25px;
} */
</style>

// src/components/Dashboard/index.jsx
import React from "react";
import { Link } from "react-router-dom";
require("./style.css");
const plusCircle = (
  <svg
    width="24"
    height="24"
    xmlns="http://www.w3.org/2000/svg"
    fill-rule="evenodd"
    clip-rule="evenodd"
    className="plusCircle"
  >
    <path d="M11.5 0c6.347 0 11.5 5.153 11.5 11.5s-5.153 11.5-11.5 11.5-11.5-5.153-11.5-11.5 5.153-11.5 11.5-11.5zm0 1c5.795 0 10.5 4.705 10.5 10.5s-4.705 10.5-10.5 10.5-10.5-4.705-10.5-10.5 4.705-10.5 10.5-10.5zm.5 10h6v1h-6v6h-1v-6h-6v-1h6v-6h1v6z" />
  </svg>
);
const Dashboard = () => {
  return (
    <aside className="dashboard">
      <h2 className="text-center">Tableau de bord</h2>
      <nav>
        <Link to="/account" class="asideNavItem text-lg-center">
          <i class="fas fa-user-circle fa-fw"></i>
          <span>Mon compte</span>
        </Link>
        <Link to="/" class="asideNavItem">
          <i class="far fa-envelope-open fa-fw"></i>
          <span>Les annonces</span>
        </Link>
        <Link to="/application" class="asideNavItem">
          {plusCircle}
          <span>J'ai postulé</span>
        </Link>
      </nav>
    </aside>
  );
};

export default Dashboard;
